import type { Character } from '../engine/types';
const rows: Omit<Character, 'code'>[] = [
  {
    name: 'The Cozy Enigma',
    tagline: 'Quietly becoming everyone’s favorite subplot.',
    description:
      'You notice the tiny things: the changed tone, the untouched fries, the friend who went quiet. You make ordinary moments feel like a place someone can land.',
    roast: 'You have a favorite mug and it has more boundaries than you do.',
    strength: 'Making people feel safe without turning it into a production.',
    growth: 'Say what you need before hoping someone notices.',
    quote: 'I made extra. Just in case.',
    color: 'lilac',
    family: 'cloud',
    tags: ['Soft-spoken', 'Present', 'Unexpectedly funny'],
  },
  {
    name: 'The Daydream Director',
    tagline: 'Physically here. Mentally in season seven.',
    description:
      'Your inner world has excellent production value. You follow a feeling into an idea, then an idea into a completely different life plan.',
    roast: 'You romanticized a trip to buy toothpaste.',
    strength: 'Finding meaning and possibility in things others walk past.',
    growth: 'Give one of those lovely ideas a deadline.',
    quote: 'Okay, but imagine if…',
    color: 'lilac',
    family: 'cloud',
    tags: ['Imaginative', 'Gentle', 'Somewhere else'],
  },
  {
    name: 'The Secret Softie',
    tagline: 'A practical plan. A suspiciously big heart.',
    description:
      'You remember how everyone takes their coffee and pretend that is just efficient logistics. Your loyalty is quiet, deliberate, and extremely well stocked.',
    roast: 'Your emergency kit includes emotional support snacks.',
    strength: 'Turning care into something people can actually use.',
    growth: 'Let someone else be the reliable one occasionally.',
    quote: 'Don’t worry. I brought a spare.',
    color: 'green',
    family: 'square',
    tags: ['Reliable', 'Thoughtful', 'Prepared'],
  },
  {
    name: 'The Lore Keeper',
    tagline: 'You remember the detail that changes everything.',
    description:
      'You connect people, patterns, and moments into a story worth keeping. Your plans have purpose, even if the purpose is a very elaborate birthday surprise.',
    roast: 'You remember what they said in 2019. With context.',
    strength: 'Seeing what matters to people over the long arc.',
    growth: 'Leave room for someone to surprise you.',
    quote: 'There’s a reason I kept that.',
    color: 'lilac',
    family: 'cloud',
    tags: ['Reflective', 'Purposeful', 'Observant'],
  },
  {
    name: 'The Deadpan Detective',
    tagline: 'Three words. Entire room destroyed.',
    description:
      'You watch, work things out, and deliver the perfect observation exactly when the conversation least expects it. Less noise, more signal.',
    roast: 'Your face says what your email politely does not.',
    strength: 'Finding the simplest explanation in a room full of drama.',
    growth: 'Share the thought before the closing credits.',
    quote: 'Interesting definition of “fine.”',
    color: 'green',
    family: 'square',
    tags: ['Dry wit', 'Practical', 'Independent'],
  },
  {
    name: 'The Rabbit Hole Resident',
    tagline: 'One quick question. Forty-seven open tabs.',
    description:
      'You follow curiosity wherever it goes. The fun is in discovering the hidden mechanism, the weird connection, the possibility everyone else dismissed.',
    roast: 'You researched a hobby so thoroughly you ran out of time to do it.',
    strength: 'Asking the question that reveals a better way.',
    growth: 'An answer does not always need another footnote.',
    quote: 'This is actually a fascinating problem.',
    color: 'lilac',
    family: 'cloud',
    tags: ['Curious', 'Inventive', 'Tab collector'],
  },
  {
    name: 'The Spreadsheet Sage',
    tagline: 'Chaos has met its project manager.',
    description:
      'You make the moving parts make sense. While everyone debates the vibe, you quietly arrange the steps that get the whole cast home.',
    roast: 'Your vacation has acceptance criteria.',
    strength: 'Making complicated situations manageable and dependable.',
    growth: 'Some excellent moments will never fit in a cell.',
    quote: 'I made a quick sheet.',
    color: 'green',
    family: 'square',
    tags: ['Precise', 'Steady', 'Suspiciously organized'],
  },
  {
    name: 'The Quiet Mastermind',
    tagline: 'Already three plot twists ahead.',
    description:
      'You like your solitude, your systems, and a plan with a point. You see how the pieces could fit, then patiently build the version that works.',
    roast: 'You have a five-year plan for your five-year plan.',
    strength: 'Turning a long-range idea into a coherent strategy.',
    growth: 'Invite people into the draft, not just the final presentation.',
    quote: 'I think there’s a better system.',
    color: 'green',
    family: 'square',
    tags: ['Strategic', 'Independent', 'Intentional'],
  },
  {
    name: 'The Human Confetti',
    tagline: 'An ordinary Tuesday? Not on your watch.',
    description:
      'You bring warmth into a room and people into the moment. Life happens in real time, and you would hate for anyone to miss the good bit.',
    roast: 'You said “one drink” with the confidence of a fictional character.',
    strength: 'Making people feel included right now.',
    growth: 'Check your own battery before charging everybody else’s.',
    quote: 'Wait. We should celebrate this.',
    color: 'peach',
    family: 'flower',
    tags: ['Warm', 'Spontaneous', 'Fully here'],
  },
  {
    name: 'The Lovable Menace',
    tagline: 'Good intentions. Historically interesting execution.',
    description:
      'You turn “what if” into “we’re doing it.” Enthusiasm is your operating system, and your favorite plans begin with someone saying this is probably a bad idea.',
    roast: 'You are the reason the group chat needs a pinned disclaimer.',
    strength: 'Helping people imagine a life a little bigger than the usual.',
    growth: 'Make sure the people in your adventure opted in.',
    quote: 'Hear me out. No, really.',
    color: 'peach',
    family: 'spark',
    tags: ['Inventive', 'Big feelings', 'Plot generator'],
  },
  {
    name: 'The Group Chat Parent',
    tagline: 'Everyone’s invited. Everyone’s hydrated.',
    description:
      'You hold the group together with practical kindness. The reservation exists, the shy friend has a seat, and someone remembered the birthday candles. You did.',
    roast: 'You have said “text me when you get home” to a taxi driver.',
    strength: 'Creating belonging that people can count on.',
    growth: 'An unanswered message is not automatically your responsibility.',
    quote: 'Has everyone eaten?',
    color: 'green',
    family: 'flower',
    tags: ['Caring', 'Organized', 'The glue'],
  },
  {
    name: 'The Hype Architect',
    tagline: 'Building a better world. Starting with this group chat.',
    description:
      'You can see what people could become and you have a plan to get them there. Part cheerleader, part director, entirely invested in the ensemble.',
    roast: 'Your pep talk accidentally became a three-part workshop.',
    strength: 'Bringing people together around a meaningful possibility.',
    growth: 'Ask whether they want encouragement or just company.',
    quote: 'I genuinely think you could do this.',
    color: 'peach',
    family: 'flower',
    tags: ['Encouraging', 'Visionary', 'People magnet'],
  },
  {
    name: 'The Plot Instigator',
    tagline: 'Making decisions the writers will have to explain.',
    description:
      'You act fast, read the room, and figure things out on your feet. If the plan falls apart, that is simply when the interesting part starts.',
    roast: '“It’ll be fine” is doing a lot of unpaid labor in your life.',
    strength: 'Staying resourceful when nobody knows the next step.',
    growth: 'A five-minute pause is also a bold move.',
    quote: 'Okay. New plan.',
    color: 'peach',
    family: 'spark',
    tags: ['Bold', 'Resourceful', 'Fast-moving'],
  },
  {
    name: 'The Chaos Theorist',
    tagline: 'A provocative idea with excellent comedic timing.',
    description:
      'You love a possibility, a debate, and the moment an old assumption falls over. Conversation is your laboratory. Yes, you might accidentally set something on fire.',
    roast: 'You played devil’s advocate at a birthday dinner.',
    strength: 'Opening up options that a room had stopped considering.',
    growth: 'Being interesting and being helpful are sometimes different jobs.',
    quote: 'Let me challenge that premise.',
    color: 'peach',
    family: 'spark',
    tags: ['Quick-witted', 'Experimental', 'Incorrigible'],
  },
  {
    name: 'The Executive Producer',
    tagline: 'This episode will be delivered on schedule.',
    description:
      'You create momentum by making decisions clear. You know what needs doing, who can do it, and which unnecessary meeting can be safely replaced with lunch.',
    roast: 'You appointed yourself captain of an elevator.',
    strength: 'Getting a group from good intentions to a finished thing.',
    growth: 'Not every conversation needs an action item.',
    quote: 'Who owns the next step?',
    color: 'green',
    family: 'square',
    tags: ['Decisive', 'Direct', 'Gets it done'],
  },
  {
    name: 'The Main Character CEO',
    tagline: 'Big vision. Bigger calendar invite.',
    description:
      'You think in possibilities and move in plans. You do not just want an interesting future; you want to assemble the team and build it.',
    roast: 'You turned a casual dinner into a founding team.',
    strength: 'Making an ambitious direction feel actionable.',
    growth: 'Let other people write some of the plot.',
    quote: 'Here’s what we’re going to build.',
    color: 'peach',
    family: 'spark',
    tags: ['Ambitious', 'Strategic', 'Magnetic'],
  },
];
export const CHARACTERS: readonly Character[] = rows.map((row, index) => ({
  ...row,
  code: index.toString(2).padStart(4, '0'),
}));
export function getCharacter(code: string): Character {
  const character = CHARACTERS.find((c) => c.code === code);
  if (!character) throw new Error('Unknown character code');
  return character;
}
