steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, '-f', Dockerfile.firebase, '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/plottwist:firebase', '.']
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/plottwist:firebase'
